# Generated by Django 6.0.1 on 2026-01-23 22:56

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_level', models.IntegerField()),
                ('period', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('grade_level', 'course_name'), name='course')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('file_urls', models.JSONField(blank=True, default=list, help_text='Public Cloudflare R2 URLs', null=True, validators=[api.models.valisdate_file_url_list])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade_level', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('files', models.URLField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('score_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('not_due_yet', 'Not due yet(Not turned in)'), ('turned_in', 'Turned in(Ready for grading)'), ('missing', 'Missing'), ('late', 'Late(Graded)'), ('graded', 'Graded')], default='not_due_yet', max_length=11)),
                ('assignment_id', models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='api.assignment')),
                ('student_id', models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='api.student')),
            ],
            options={
                'unique_together': {('student_id', 'assignment_id')},
            },
        ),
    ]
