# Generated by Django 5.1.6 on 2025-03-05 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_level', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('grade_level', 'course_name'), name='course')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
                ('files', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='api.assignment')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('files', models.TextField()),
                ('status', models.CharField(choices=[('turned_in', 'Turned in'), ('missing', 'Missing'), ('late', 'Late'), ('not_due_yet', 'Not due yet')], default='not_due_yet', max_length=11)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_id', 'course_id'), name='student_course')],
            },
        ),
    ]
