# Generated by Django 5.1.6 on 2025-03-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='as_student', to='api.course'),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
