# Generated by Django 6.0.1 on 2026-02-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='example_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
