# Generated by Django 5.1.6 on 2025-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publication_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='api.course'),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
