# Generated by Django 5.1.6 on 2025-03-09 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='api.student'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='api.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student_id', 'assignment_id')},
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
