# Generated by Django 5.1.6 on 2025-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_submission_student_id_alter_submission_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.TextField(null=True),
        ),
    ]
