# Generated by Django 5.1.6 on 2025-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_submission_content_alter_submission_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
