# Generated by Django 5.1.6 on 2025-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_submission_content_alter_submission_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('not_due_yet', 'Not due yet'), ('turned_in', 'Turned in'), ('missing', 'Missing'), ('late', 'Late(Graded)')], default='not_due_yet', max_length=11),
        ),
        migrations.DeleteModel(
            name='grade',
        ),
    ]
