# Generated by Django 5.1.6 on 2025-03-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_submission_score_submission_score_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('not_due_yet', 'Not due yet(Not turned in)'), ('turned_in', 'Turned in(Ready for grading)'), ('missing', 'Missing'), ('late', 'Late(Graded)')], default='not_due_yet', max_length=11),
        ),
    ]
