# Generated by Django 6.0.1 on 2026-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_assignment_due_alter_assignment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
