# Generated by Django 6.0.1 on 2026-01-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_submission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text='Public Cloudflare R2 URLs'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
