# Generated by Django 6.0.1 on 2026-01-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_assignment_files_alter_submission_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text='Public Cloudflare R2 URLs', null=True),
        ),
    ]
