# Generated by Django 6.0.1 on 2026-01-16 05:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_assignment_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='files',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_urls',
            field=models.JSONField(blank=True, default=list, help_text='Public Cloudflare R2 URLs', null=True, validators=[api.models.valisdate_file_url_list]),
        ),
    ]
