# Generated by Django 6.0.1 on 2026-01-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_assignment_files_assignment_file_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='file_urls',
            new_name='files',
        ),
    ]
