# Generated by Django 6.0.1 on 2026-01-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_file_urls_assignment_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='files',
            new_name='file_urls',
        ),
    ]
