# Generated by Django 6.0.1 on 2026-01-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
