# Generated by Django 6.0.1 on 2026-01-23 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_student_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade_level', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.course')),
            ],
        ),
    ]
